[workspace]
resolver = "2"
default-members = ["doppleganger"]
members = [
  "doppleganger",
  "doppleganger-core",
  "doppleganger-macros",
  "doppleganger-macros-parse",
  "examples",
]


[workspace.dependencies]
unsynn = "0.3"
quote = "1"
proc-macro2 = "1"
