[package]
name = "doppleganger-examples"
version = "0.2.0"
edition = "2024"
publish = false

[dependencies]
doppleganger = { path = "../doppleganger" }

[[example]]
name = "basic_usage"
path = "basic_usage.rs"
